@baseUrl = http://localhost:443
@videoID = d186543129e295769599eb390e7934765658136ccb3811766b226696ae78d34a

###

# Add a marker to a video
POST {{baseUrl}}/api/v1/videos/{{videoID}}/markers
Content-Type: application/json
Accept: application/json

{
  "timeSecond": 60,
  "label": "Intro",
  "description": "Start of the video"
}


### 

# Get markers for a video
GET {{baseUrl}}/api/v1/videos/{{videoID}}/markers   
