@baseUrl = http://localhost:4040
@session_id = 29eb95aa-a7f7-4ede-b830-f29ba83d28b9
@username = user

###

# Get user favorites
GET {{baseUrl}}/api/v1/users/{{username}}/favorites
Accept: application/json
Cookie: session_id={{session_id}}

###

# Update user favorites (replace with valid video IDs)
POST {{baseUrl}}/api/v1/users/{{username}}/favorites
Content-Type: application/json
Accept: application/json
Cookie: session_id={{session_id}}

{
  "favorites": [
    "5fe0c0f695bbb3e575b4ce215985c6982702b6d028e2d2db21ef72f4bcabe0df"
  ]
}
