@baseUrl = http://localhost:443
@session_id = 9415a7e0-b1ca-4016-bc84-260e08084680
@username = user
@password = pass

###

# Login Request
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

# Change Password Request
POST {{baseUrl}}/api/v1/auth/password
Content-Type: application/json
Accept: application/json
Cookie: session_id={{session_id}}

{
  "oldpassword": "pass",
  "newpassword": "pass"
}


###

# Logout
POST {{baseUrl}}/api/v1/auth/logout
Accept: application/json
Cookie: session_id={{session_id}}

###

# Check authentication status
GET {{baseUrl}}/api/v1/auth/status
Accept: application/json
Cookie: session_id={{session_id}}
