@baseUrl = http://localhost:443/api/v1
@session_id = ae37adcc-db9d-495d-b5b1-fd5e4491f42e
@username = user
@password = pass

###

# Get User Playlists
GET {{baseUrl}}/users/{{username}}/playlists
Accept: application/json
Cookie: session_id={{session_id}}

###

# Create User Playlist
POST {{baseUrl}}/users/{{username}}/playlists
Content-Type: application/json
Accept: application/json
Cookie: session_id={{session_id}}

{
  "title": "New Playlist",
  "description": "A new playlist created via test client"
}

###

# Get User Playlist By Slug
GET {{baseUrl}}/users/user/playlists/super-cute
Accept: application/json
Cookie: session_id={{session_id}}

###

# Delete User Playlist By Slug
DELETE {{baseUrl}}/users/{{username}}/playlists/{{slug}}
Accept: application/json
Cookie: session_id={{session_id}}

###

# Add Video to Playlist
POST {{baseUrl}}/users/{{username}}/playlists/new/videos
Content-Type: application/json
Accept: application/json
Cookie: session_id={{session_id}}

{
  "videoId": "some-video-id"
}

###

# Delete Video from Playlist
DELETE {{baseUrl}}/users/{{username}}/playlists/{{slug}}/videos/{{videoId}}
Accept: application/json
Cookie: session_id={{session_id}}

###

# Set User Playlists Order
PUT {{baseUrl}}/users/{{username}}/playlists/order
Content-Type: application/json
Accept: application/json
Cookie: session_id={{session_id}}

{
  "order": ["playlist1", "playlist2", "playlist3"]
}

###

# Update User Playlist Info
PUT {{baseUrl}}/users/{{username}}/playlists/{{slug}}
Content-Type: application/json
Accept: application/json
Cookie: session_id={{session_id}}

{
  "title": "Updated Playlist Title",
  "description": "Updated description of the playlist"
}

###
