@baseUrl = http://localhost:4040
@videoId = 087be485e0acad6fb1ba026e75542fed5f52e073496c649bc4a3ce345a63f48f

###

# Get rating and views for a video
GET {{baseUrl}}/api/v1/rate/{{videoId}}
Accept: application/json

###

# Post a rating for a video (rating between 1 and 5)
POST {{baseUrl}}/api/v1/rate/{{videoId}}
Content-Type: application/json
Accept: application/json

{
  "rating": 5
}
