// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: ovaproto.proto

// The package name creates a namespace for your messages

package ovaproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OvaService_GetNextJob_FullMethodName     = "/ovagrpc.OvaService/GetNextJob"
	OvaService_Heartbeat_FullMethodName      = "/ovagrpc.OvaService/Heartbeat"
	OvaService_SayHello_FullMethodName       = "/ovagrpc.OvaService/SayHello"
	OvaService_StreamProgress_FullMethodName = "/ovagrpc.OvaService/StreamProgress"
)

// OvaServiceClient is the client API for OvaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service defines the "actions" your Go server and Rust worker can perform.
type OvaServiceClient interface {
	// Unary RPC: Rust asks for a job, Go sends one back.
	GetNextJob(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*Job, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// Server Streaming: Rust sends continuous progress updates to Go.
	StreamProgress(ctx context.Context, in *ProgressUpdate, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
}

type ovaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOvaServiceClient(cc grpc.ClientConnInterface) OvaServiceClient {
	return &ovaServiceClient{cc}
}

func (c *ovaServiceClient) GetNextJob(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, OvaService_GetNextJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ovaServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, OvaService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ovaServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, OvaService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ovaServiceClient) StreamProgress(ctx context.Context, in *ProgressUpdate, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OvaService_ServiceDesc.Streams[0], OvaService_StreamProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProgressUpdate, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OvaService_StreamProgressClient = grpc.ServerStreamingClient[StreamResponse]

// OvaServiceServer is the server API for OvaService service.
// All implementations must embed UnimplementedOvaServiceServer
// for forward compatibility.
//
// The service defines the "actions" your Go server and Rust worker can perform.
type OvaServiceServer interface {
	// Unary RPC: Rust asks for a job, Go sends one back.
	GetNextJob(context.Context, *WorkerInfo) (*Job, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	// Server Streaming: Rust sends continuous progress updates to Go.
	StreamProgress(*ProgressUpdate, grpc.ServerStreamingServer[StreamResponse]) error
	mustEmbedUnimplementedOvaServiceServer()
}

// UnimplementedOvaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOvaServiceServer struct{}

func (UnimplementedOvaServiceServer) GetNextJob(context.Context, *WorkerInfo) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNextJob not implemented")
}
func (UnimplementedOvaServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedOvaServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedOvaServiceServer) StreamProgress(*ProgressUpdate, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamProgress not implemented")
}
func (UnimplementedOvaServiceServer) mustEmbedUnimplementedOvaServiceServer() {}
func (UnimplementedOvaServiceServer) testEmbeddedByValue()                    {}

// UnsafeOvaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OvaServiceServer will
// result in compilation errors.
type UnsafeOvaServiceServer interface {
	mustEmbedUnimplementedOvaServiceServer()
}

func RegisterOvaServiceServer(s grpc.ServiceRegistrar, srv OvaServiceServer) {
	// If the following call panics, it indicates UnimplementedOvaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OvaService_ServiceDesc, srv)
}

func _OvaService_GetNextJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvaServiceServer).GetNextJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OvaService_GetNextJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvaServiceServer).GetNextJob(ctx, req.(*WorkerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _OvaService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvaServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OvaService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvaServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OvaService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvaServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OvaService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvaServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OvaService_StreamProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProgressUpdate)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OvaServiceServer).StreamProgress(m, &grpc.GenericServerStream[ProgressUpdate, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OvaService_StreamProgressServer = grpc.ServerStreamingServer[StreamResponse]

// OvaService_ServiceDesc is the grpc.ServiceDesc for OvaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OvaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ovagrpc.OvaService",
	HandlerType: (*OvaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNextJob",
			Handler:    _OvaService_GetNextJob_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _OvaService_Heartbeat_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _OvaService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProgress",
			Handler:       _OvaService_StreamProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ovaproto.proto",
}
