// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ovaproto.proto

// The package name creates a namespace for your messages

package ovaproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`      // Useful for the dashboard
	RamUsage      float32                `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`      // Useful for the dashboard
	ActiveJobs    int32                  `protobuf:"varint,4,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"` // Tells Go how busy the worker is
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_ovaproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovaproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_ovaproto_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // Go can return 'false' if worker needs to restart
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_ovaproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovaproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_ovaproto_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_ovaproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovaproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_ovaproto_proto_rawDescGZIP(), []int{2}
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_ovaproto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovaproto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_ovaproto_proto_rawDescGZIP(), []int{3}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Data sent from the Rust worker to identify itself.
type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SystemLoad    string                 `protobuf:"bytes,2,opt,name=system_load,json=systemLoad,proto3" json:"system_load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_ovaproto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ovaproto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_ovaproto_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetSystemLoad() string {
	if x != nil {
		return x.SystemLoad
	}
	return ""
}

// Data sent from the Go server to tell Rust what to do.
type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	VideoPath     string                 `protobuf:"bytes,2,opt,name=video_path,json=videoPath,proto3" json:"video_path,omitempty"`
	TargetFormat  string                 `protobuf:"bytes,3,opt,name=target_format,json=targetFormat,proto3" json:"target_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_ovaproto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_ovaproto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_ovaproto_proto_rawDescGZIP(), []int{5}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetVideoPath() string {
	if x != nil {
		return x.VideoPath
	}
	return ""
}

func (x *Job) GetTargetFormat() string {
	if x != nil {
		return x.TargetFormat
	}
	return ""
}

// Data for progress tracking.
type ProgressUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Percentage     float32                `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	BytesProcessed int64                  `protobuf:"varint,3,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_ovaproto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_ovaproto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_ovaproto_proto_rawDescGZIP(), []int{6}
}

func (x *ProgressUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressUpdate) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ProgressUpdate) GetBytesProcessed() int64 {
	if x != nil {
		return x.BytesProcessed
	}
	return 0
}

// Simple confirmation message.
type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Progress      float32                `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_ovaproto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovaproto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_ovaproto_proto_rawDescGZIP(), []int{7}
}

func (x *StreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_ovaproto_proto protoreflect.FileDescriptor

const file_ovaproto_proto_rawDesc = "" +
	"\n" +
	"\x0eovaproto.proto\x12\aovagrpc\"\x8a\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x02R\bramUsage\x12\x1f\n" +
	"\vactive_jobs\x18\x04 \x01(\x05R\n" +
	"activeJobs\"+\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\x0e\n" +
	"\fHelloRequest\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"J\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vsystem_load\x18\x02 \x01(\tR\n" +
	"systemLoad\"`\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"video_path\x18\x02 \x01(\tR\tvideoPath\x12#\n" +
	"\rtarget_format\x18\x03 \x01(\tR\ftargetFormat\"p\n" +
	"\x0eProgressUpdate\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x02R\n" +
	"percentage\x12'\n" +
	"\x0fbytes_processed\x18\x03 \x01(\x03R\x0ebytesProcessed\"F\n" +
	"\x0eStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x02R\bprogress2\x82\x02\n" +
	"\n" +
	"OvaService\x12/\n" +
	"\n" +
	"GetNextJob\x12\x13.ovagrpc.WorkerInfo\x1a\f.ovagrpc.Job\x12B\n" +
	"\tHeartbeat\x12\x19.ovagrpc.HeartbeatRequest\x1a\x1a.ovagrpc.HeartbeatResponse\x129\n" +
	"\bSayHello\x12\x15.ovagrpc.HelloRequest\x1a\x16.ovagrpc.HelloResponse\x12D\n" +
	"\x0eStreamProgress\x12\x17.ovagrpc.ProgressUpdate\x1a\x17.ovagrpc.StreamResponse0\x01B\x17Z\x15ovacli/proto;ovaprotob\x06proto3"

var (
	file_ovaproto_proto_rawDescOnce sync.Once
	file_ovaproto_proto_rawDescData []byte
)

func file_ovaproto_proto_rawDescGZIP() []byte {
	file_ovaproto_proto_rawDescOnce.Do(func() {
		file_ovaproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ovaproto_proto_rawDesc), len(file_ovaproto_proto_rawDesc)))
	})
	return file_ovaproto_proto_rawDescData
}

var file_ovaproto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ovaproto_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),  // 0: ovagrpc.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 1: ovagrpc.HeartbeatResponse
	(*HelloRequest)(nil),      // 2: ovagrpc.HelloRequest
	(*HelloResponse)(nil),     // 3: ovagrpc.HelloResponse
	(*WorkerInfo)(nil),        // 4: ovagrpc.WorkerInfo
	(*Job)(nil),               // 5: ovagrpc.Job
	(*ProgressUpdate)(nil),    // 6: ovagrpc.ProgressUpdate
	(*StreamResponse)(nil),    // 7: ovagrpc.StreamResponse
}
var file_ovaproto_proto_depIdxs = []int32{
	4, // 0: ovagrpc.OvaService.GetNextJob:input_type -> ovagrpc.WorkerInfo
	0, // 1: ovagrpc.OvaService.Heartbeat:input_type -> ovagrpc.HeartbeatRequest
	2, // 2: ovagrpc.OvaService.SayHello:input_type -> ovagrpc.HelloRequest
	6, // 3: ovagrpc.OvaService.StreamProgress:input_type -> ovagrpc.ProgressUpdate
	5, // 4: ovagrpc.OvaService.GetNextJob:output_type -> ovagrpc.Job
	1, // 5: ovagrpc.OvaService.Heartbeat:output_type -> ovagrpc.HeartbeatResponse
	3, // 6: ovagrpc.OvaService.SayHello:output_type -> ovagrpc.HelloResponse
	7, // 7: ovagrpc.OvaService.StreamProgress:output_type -> ovagrpc.StreamResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ovaproto_proto_init() }
func file_ovaproto_proto_init() {
	if File_ovaproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ovaproto_proto_rawDesc), len(file_ovaproto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ovaproto_proto_goTypes,
		DependencyIndexes: file_ovaproto_proto_depIdxs,
		MessageInfos:      file_ovaproto_proto_msgTypes,
	}.Build()
	File_ovaproto_proto = out.File
	file_ovaproto_proto_goTypes = nil
	file_ovaproto_proto_depIdxs = nil
}
